"""New in this set: the day's mood, your data, start and end of the day."""

FACE = [
    '................',
    '.....KKKKKK.....',
    '...KKXXXXXXKK...',
    '..KXXXXXXXXXXK..',
    '.KXXXXXXXXXXXXK.',
    '.KXXXXXXXXXXXXK.',
    'KXXXXXXXXXXXXXXK',
    'KXXXXXXXXXXXXXXK',
    'KXXXXXXXXXXXXXXK',
    'KXXXXXXXXXXXXXxK',
    '.KXXXXXXXXXXXxK.',
    '.KXXXXXXXXXXXxK.',
    '..KXXXXXXXXXxK..',
    '...KKxxxxxxKK...',
    '.....KKKKKK.....',
    '................',
]


def face(fill: str, shade: str, features: str) -> str:
    marks = [row.strip() for row in features.strip().splitlines()]
    rows = []
    for y, row in enumerate(FACE):
        out = []
        for x, ch in enumerate(row):
            mark = marks[y][x] if y < len(marks) else '.'
            if ch in 'Xx' and mark != '.':
                out.append(mark)
            else:
                out.append({'X': fill, 'x': shade}.get(ch, ch))
        rows.append(''.join(out))
    return '\n'.join(rows)


ICONS = {
    'mood_great': face('Y', 'y', """
        ................
        ................
        ................
        ................
        ....KK....KK....
        ...K..K..K..K...
        ................
        ................
        ...KKKKKKKKKK...
        ...KWWWWWWWWK...
        ....KEEEEEEK....
        .....KKKKKK.....
    """),
    'mood_good': face('Y', 'y', """
        ................
        ................
        ................
        ................
        ....KK....KK....
        ....KK....KK....
        ................
        ................
        ...K........K...
        ....K......K....
        .....KKKKKK.....
    """),
    'mood_loaded': face('O', 'o', """
        ................
        ................
        ................
        ...KKK....KKK...
        ................
        ....KK....KK....
        ................
        ................
        ................
        ....KKKKKKKK....
        ................
    """),
    'mood_bad': face('U', 'B', """
        ................
        ................
        ................
        ...KK......KK...
        .....K....K.....
        ....KK....KK....
        ....W.......U...
        ....W...........
        .....KKKKKK.....
        ....K......K....
        ...K........K...
    """),
    'trash': """
        ................
        ......KKKK......
        .....KK..KK.....
        ..KKKKKKKKKKKK..
        ..KNNNNNNNNNNK..
        ..KKKKKKKKKKKK..
        ...KwKNKNKNnK...
        ...KwKNKNKNnK...
        ...KwKNKNKNnK...
        ...KwKNKNKNnK...
        ...KwKNKNKNnK...
        ...KwKNKNKNnK...
        ...KwKNKNKNnK...
        ...KnnnnnnnnK...
        ....KKKKKKKK....
        ................
    """,
    'export': """
        ................
        .......KK.......
        ......KGGK......
        ......KGGK......
        ......KGGK......
        ......KGGK......
        ...KKKKGGKKKK...
        ...KGGGGGGGgK...
        ....KGGGGGgK....
        .....KGGGgK.....
        .K....KGgK....K.
        .KK....KK....KK.
        .KNK........KnK.
        .KNKKKKKKKKKKnK.
        .KwNNNNNNNNNNnK.
        .KKKKKKKKKKKKKK.
    """,
    'import': """
        ................
        .......KK.......
        ......KGgK......
        .....KGGGgK.....
        ....KGGGGGgK....
        ...KGGGGGGGgK...
        ...KKKKGgKKKK...
        ......KGgK......
        ......KGgK......
        ......KGgK......
        .K....KGgK....K.
        .KK...KKKK...KK.
        .KNK........KnK.
        .KNKKKKKKKKKKnK.
        .KwNNNNNNNNNNnK.
        .KKKKKKKKKKKKKK.
    """,
    'sunrise': """
        .......KK.......
        ......KGGK......
        .....KGGGGK.....
        .......GG.......
        ..K....KK....K..
        ...K........K...
        ......KKKK......
        .....KYYYYK.....
        .K..KYZZYYyK..K.
        ...KYZYYYYYyK...
        ..KYYYYYYYYYyK..
        KKKKKKKKKKKKKKKK
        KkkkkkkkkkkkkkkK
        KCCCCCCCCCCCCCCK
        KKKKKKKKKKKKKKKK
        ................
    """,
    'sunset': """
        .......GG.......
        .....KGGGGK.....
        ......KGGK......
        .......KK.......
        ..K..........K..
        ...K........K...
        ......KKKK......
        .....KOOOOK.....
        .K..KOYYOOoK..K.
        ...KOYOOOOOoK...
        ..KOOOOOOOOOoK..
        KKKKKKKKKKKKKKKK
        KvvvvvvvvvvvvvvK
        KVVVVVVVVVVVVVVK
        KKKKKKKKKKKKKKKK
        ................
    """,
    'shield': """
        ................
        ..KKKKKKKKKKKK..
        ..KlGGGGGGGGgK..
        ..KGGGGGGGGGgK..
        ..KGGGGGGGWGgK..
        ..KGGGGGGWWGgK..
        ..KGWGGGWWGGgK..
        ..KGWWGWWGGGgK..
        ..KGGWWWGGGGgK..
        ...KGGWGGGGgK...
        ...KGGGGGGGgK...
        ....KGGGGGgK....
        .....KGGGgK.....
        ......KGgK......
        .......KK.......
        ................
    """,
}
