"""Builds Breakbit's pixel icons from their grids (scripts/pixel-icons/icons/*.py).

Each icon is a 16x16 grid of palette characters (palette.py). The build checks every
grid and writes:
- public/icons/<name>.svg: one rectangle per run of a colour, with crisp edges, so it
  stays sharp at 16, 24, 32 or 48 px on any screen;
- public/icons/notify/<name>.png: 96 px PNGs for the icons notifications use (they need
  a bitmap);
- src/ui/icons/iconNames.ts: the typed list of names.

    python3 scripts/pixel-icons/build.py
"""
import importlib.util
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))
from palette import PALETTE, SIZE, TRANSPARENT  # noqa: E402

OUT = ROOT / 'public/icons'
NAMES_TS = ROOT / 'src/ui/icons/iconNames.ts'
# Shown in notifications (app/engine/notificationContent.ts).
NOTIFY = ('stretch', 'sun', 'goal', 'moon')
NOTIFY_SCALE = 6


def parse(name: str, art: str) -> list[str]:
    rows = [row.strip() for row in art.strip().splitlines()]
    if len(rows) != SIZE:
        raise ValueError(f'{name}: {len(rows)} rows, expected {SIZE}')
    for y, row in enumerate(rows):
        if len(row) != SIZE:
            raise ValueError(f'{name}: row {y} has {len(row)} columns, expected {SIZE}')
        unknown = set(row) - set(PALETTE) - {TRANSPARENT}
        if unknown:
            raise ValueError(f'{name}: row {y} uses unknown colours {sorted(unknown)}')
    return rows


def load_icons(categories: list[str] | None = None) -> dict[str, list[str]]:
    """Every icon by name, category by category (file order), checked."""
    icons: dict[str, list[str]] = {}
    for path in sorted((HERE / 'icons').glob('*.py')):
        # _shapes.py and the like are helpers, not a category.
        if path.stem.startswith('_') or (categories and path.stem not in categories):
            continue
        spec = importlib.util.spec_from_file_location(path.stem, path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        for name, art in module.ICONS.items():
            if name in icons:
                raise ValueError(f'{name}: defined twice')
            icons[name] = parse(name, art)
    return icons


def svg(rows: list[str]) -> str:
    """Horizontal runs of one colour become one rectangle each, grouped by colour."""
    by_colour: dict[str, list[str]] = {}
    for y, row in enumerate(rows):
        x = 0
        while x < SIZE:
            ch = row[x]
            end = x
            while end < SIZE and row[end] == ch:
                end += 1
            if ch != TRANSPARENT:
                by_colour.setdefault(PALETTE[ch], []).append(f'M{x} {y}h{end - x}v1h{x - end}z')
            x = end
    paths = ''.join(f'<path fill="{colour}" d="{"".join(d)}"/>' for colour, d in by_colour.items())
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}" '
        f'shape-rendering="crispEdges">{paths}</svg>\n'
    )


def png(rows: list[str], scale: int):
    from PIL import Image, ImageDraw

    image = Image.new('RGBA', (SIZE * scale, SIZE * scale), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch != TRANSPARENT:
                draw.rectangle(
                    [x * scale, y * scale, (x + 1) * scale - 1, (y + 1) * scale - 1],
                    fill=PALETTE[ch],
                )
    return image


def main() -> None:
    icons = load_icons()
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / 'notify').mkdir(exist_ok=True)
    for old in OUT.glob('*.svg'):
        if old.stem not in icons:
            old.unlink()
    for name, rows in icons.items():
        (OUT / f'{name}.svg').write_text(svg(rows))
    for name in NOTIFY:
        png(icons[name], NOTIFY_SCALE).save(OUT / 'notify' / f'{name}.png', optimize=True)

    names = sorted(icons)
    NAMES_TS.write_text(
        '// Generated by scripts/pixel-icons/build.py — do not edit by hand.\n'
        'export const ICON_NAMES = [\n'
        + ''.join(f"  '{name}',\n" for name in names)
        + '] as const;\n\nexport type IconName = (typeof ICON_NAMES)[number];\n'
    )
    print(f'{len(icons)} icons → public/icons, {len(NOTIFY)} notification PNGs, iconNames.ts')


if __name__ == '__main__':
    main()
