"""Imports the icon set drawn by an image AI (docs/prompts-iconos.md) as 32x32 sprites.

    python3 scripts/pixel-icons/import.py ~/Downloads/breakbit-iconos.zip   (or a folder)

Each sheet (sheets.py) holds one icon per cell. For every icon:
1. Hard transparency. The AI doesn't keep to the cells exactly (a drawing may spill a few
   pixels into the next one), so each icon is the biggest part in its cell plus the
   smaller parts nearest to it; loose specks are dropped.
2. The drawing is cut out and centred in a square, so every icon has the same optical
   size whatever the AI drew.
3. It is resampled to 28x28 art pixels (2-pixel margin in a 32x32 sprite), each pixel
   taking the dominant colour of its block. The AI's "pixels" don't sit on a regular grid
   (8–10 px), so sampling the drawing itself keeps it crisp and faithful.
4. Palette: at most 32 colours per icon (max coverage), no dithering.

Writes public/icons/<name>.png, the notification bitmaps (public/icons/notify, 192 px)
and src/ui/icons/iconNames.ts. Needs Pillow only.
"""
import sys
import tempfile
import zipfile
from collections import Counter
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))
from sheets import SHEET_SIZE, SHEETS, SPRITE  # noqa: E402

OUT = ROOT / 'public/icons'
NAMES_TS = ROOT / 'src/ui/icons/iconNames.ts'
ART = 28
COLOURS = 32
# Specks smaller than this (in sheet pixels) are noise, not part of the icon.
MIN_PART = 60
# A smaller part joins the nearest icon only if it is this close (sparkles, rays, "zz").
MAX_GAP = 48
# Shown in notifications (app/engine/notificationContent.ts): they need a bitmap.
NOTIFY = ('stretch', 'sun', 'goal', 'moon')
NOTIFY_SCALE = 6


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    with tempfile.TemporaryDirectory() as tmp:
        source = unpack(Path(sys.argv[1]).expanduser(), Path(tmp))
        files = {path.name: path for path in source.rglob('*.png')}
        missing = [file for file, *_ in SHEETS if file not in files]
        if missing:
            sys.exit(f'Faltan hojas: {", ".join(missing)}')
        sprites = {}
        for file, _title, cols, rows, items in SHEETS:
            sheet = Image.open(files[file]).convert('RGBA')
            if sheet.size != (SHEET_SIZE, SHEET_SIZE):
                sheet = sheet.resize((SHEET_SIZE, SHEET_SIZE), Image.Resampling.NEAREST)
            drawings = icon_masks(sheet, (cols, rows), len(items), file)
            pixels = sheet.load()
            for (name, _), mask in zip(items, drawings):
                sprites[name] = convert(pixels, mask)

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / 'notify').mkdir(exist_ok=True)
    for old in [*OUT.glob('*.png'), *OUT.glob('*.svg')]:
        old.unlink()
    for name, sprite in sprites.items():
        sprite.save(OUT / f'{name}.png', optimize=True)
    for name in NOTIFY:
        big = sprites[name].resize((SPRITE * NOTIFY_SCALE,) * 2, Image.Resampling.NEAREST)
        big.save(OUT / 'notify' / f'{name}.png', optimize=True)

    names = sorted(sprites)
    NAMES_TS.write_text(
        '// Generated by scripts/pixel-icons/import.py — do not edit by hand.\n'
        'export const ICON_NAMES = [\n'
        + ''.join(f"  '{name}',\n" for name in names)
        + '] as const;\n\nexport type IconName = (typeof ICON_NAMES)[number];\n'
    )
    size = sum((OUT / f'{name}.png').stat().st_size for name in names)
    print(f'{len(names)} iconos ({size // 1024} KB) → public/icons, {len(NOTIFY)} para avisos, iconNames.ts')


def unpack(path: Path, tmp: Path) -> Path:
    if path.is_dir():
        return path
    if path.suffix == '.zip':
        with zipfile.ZipFile(path) as archive:
            archive.extractall(tmp)
        return tmp
    sys.exit(f'No es una carpeta ni un .zip: {path}')


def icon_masks(sheet: Image.Image, grid: tuple[int, int], count: int, file: str) -> list[set]:
    """The pixels of each icon: its cell's biggest part plus the small parts nearest to it."""
    cols, rows = grid
    cell_w, cell_h = SHEET_SIZE // cols, SHEET_SIZE // rows
    parts = [part for part in components(sheet) if len(part) >= MIN_PART]
    boxes = [bounds(part) for part in parts]

    def cell_of(box) -> int:
        x = min(int((box[0] + box[2]) / 2 // cell_w), cols - 1)
        y = min(int((box[1] + box[3]) / 2 // cell_h), rows - 1)
        return y * cols + x

    mains: list[int] = []
    for index in range(count):
        inside = [i for i, box in enumerate(boxes) if cell_of(box) == index]
        if not inside:
            sys.exit(f'{file}: la celda {index + 1} está vacía')
        mains.append(max(inside, key=lambda i: len(parts[i])))
    masks = [set(parts[i]) for i in mains]
    for i, box in enumerate(boxes):
        if i in mains:
            continue
        gaps = [gap(box, boxes[main]) for main in mains]
        nearest = min(range(count), key=lambda k: gaps[k])
        if gaps[nearest] <= MAX_GAP:
            masks[nearest].update(parts[i])
    return masks


def components(sheet: Image.Image) -> list[list[tuple[int, int]]]:
    """Connected opaque parts of the sheet."""
    alpha = sheet.getchannel('A').load()
    width, height = sheet.size
    opaque = {(x, y) for y in range(height) for x in range(width) if alpha[x, y] >= 128}
    seen: set[tuple[int, int]] = set()
    found = []
    for start in sorted(opaque):
        if start in seen:
            continue
        part, stack = [], [start]
        seen.add(start)
        while stack:
            x, y = stack.pop()
            part.append((x, y))
            for neighbour in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
                if neighbour in opaque and neighbour not in seen:
                    seen.add(neighbour)
                    stack.append(neighbour)
        found.append(part)
    return found


def bounds(part) -> tuple[int, int, int, int]:
    xs = [x for x, _ in part]
    ys = [y for _, y in part]
    return min(xs), min(ys), max(xs) + 1, max(ys) + 1


def gap(a, b) -> int:
    """Distance between two boxes (0 if they touch or overlap)."""
    dx = max(b[0] - a[2], a[0] - b[2], 0)
    dy = max(b[1] - a[3], a[1] - b[3], 0)
    return max(dx, dy)


def convert(pixels, mask: set) -> Image.Image:
    left, top, right, bottom = bounds(mask)
    side = max(right - left, bottom - top)
    x0 = (left + right - side) / 2
    y0 = (top + bottom - side) / 2
    step = side / ART
    sprite = Image.new('RGBA', (SPRITE, SPRITE), (0, 0, 0, 0))
    out = sprite.load()
    pad = (SPRITE - ART) // 2
    for j in range(ART):
        for i in range(ART):
            # The middle of the block: its edges may belong to the neighbours.
            xa, xb = block(x0, i, step)
            ya, yb = block(y0, j, step)
            samples = [
                pixels[x, y] if (x, y) in mask else (0, 0, 0, 0)
                for y in range(ya, yb)
                for x in range(xa, xb)
            ]
            out[pad + i, pad + j] = dominant(samples)
    return reduce_palette(sprite)


def block(origin: float, index: int, step: float) -> tuple[int, int]:
    start = int(origin + index * step + step * 0.2)
    end = int(origin + (index + 1) * step - step * 0.2)
    return start, max(end, start + 1)


def dominant(samples: list[tuple[int, int, int, int]]) -> tuple[int, int, int, int]:
    colours = [sample[:3] for sample in samples if sample[3] >= 128]
    if len(colours) * 2 < len(samples):
        return (0, 0, 0, 0)
    buckets = Counter((r >> 4, g >> 4, b >> 4) for r, g, b in colours)
    top = buckets.most_common(1)[0][0]
    chosen = [c for c in colours if (c[0] >> 4, c[1] >> 4, c[2] >> 4) == top]
    return (*(round(sum(c[k] for c in chosen) / len(chosen)) for k in range(3)), 255)


def reduce_palette(sprite: Image.Image) -> Image.Image:
    alpha = sprite.getchannel('A')
    rgb = Image.new('RGB', sprite.size, (0, 0, 0))
    rgb.paste(sprite, (0, 0), sprite)
    reduced = rgb.quantize(
        colors=COLOURS, method=Image.Quantize.MAXCOVERAGE, dither=Image.Dither.NONE
    ).convert('RGBA')
    reduced.putalpha(alpha)
    return reduced


if __name__ == '__main__':
    main()
