/**
 * Generates src/ui/icons/iconNames.ts from the files in public/icons/32.
 * Run with `pnpm icons` after importing or adding icons.
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const names = readdirSync(join(root, 'public/icons/32'))
  .filter((file) => file.endsWith('.png'))
  .map((file) => file.replace(/\.png$/, ''))
  .sort();

const body = `// Generated by scripts/gen-icon-names.ts — do not edit by hand.
export const ICON_NAMES = [
${names.map((name) => `  '${name}',`).join('\n')}
] as const;

export type IconName = (typeof ICON_NAMES)[number];
`;

writeFileSync(join(root, 'src/ui/icons/iconNames.ts'), body);
console.log(`wrote ${names.length} icon names`);
