"""Builds the avatar art into public/avatar/<phase>-<pose>.png and src/assets/avatarArt.ts.

The art is drawn on a 64x64 rig (rig.py): characters.py has each phase at work (side
view), gestures.py the gestures facing you and the demo pose. PNGs at their native size
(shading makes SVGs ten times heavier); the app scales them with crisp pixels.

    python3 scripts/pixel-avatar/build.py
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))
from characters import SCENES as AT_WORK  # noqa: E402
from gestures import SCENES as GESTURES  # noqa: E402
from rig import image  # noqa: E402

OUT = ROOT / 'public/avatar'
ART_TS = ROOT / 'src/assets/avatarArt.ts'
SCENES = {**AT_WORK, **GESTURES}


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for old in [*OUT.glob('*.svg'), *OUT.glob('*.png')]:
        if old.stem not in SCENES or old.suffix == '.svg':
            old.unlink()
    for name, draw in SCENES.items():
        image(draw().render()).save(OUT / f'{name}.png', optimize=True)
    keys = sorted(name.replace('-', ':', 1) for name in SCENES)
    ART_TS.write_text(
        '// Generated by scripts/pixel-avatar/build.py — do not edit by hand.\n'
        '/** The avatar art that exists, as `phase:pose`. */\n'
        'export const AVATAR_ART = [\n'
        + ''.join(f"  '{key}',\n" for key in keys)
        + '] as const;\n'
    )
    print(f'{len(SCENES)} avatar images → public/avatar, avatarArt.ts')


if __name__ == '__main__':
    main()
