"""Imports the avatar art: 21 AI-made pixel-art PNGs (1024x1024, see docs/prompts-avatar.md)
turned into crisp 128x128 sprites for the app.

    python3 scripts/pixel-avatar/import.py ~/Downloads/breakbit-avatar.zip   (or a folder)

For each image:
1. Hard transparency: the drawing fully opaque, the background fully transparent (the
   source has 95–99 % opaque fills and faint halos).
2. Pixel grid: the art is drawn in ~8 px "pixels" that don't always sit on an exact grid.
   The 8 px offset that lines up with most colour edges is chosen, and each cell takes its
   dominant colour (its centre, so a neighbour's edge doesn't bleed in).
3. Framing: full-body poses (idle, demo) stand on the same baseline and are centred, so the
   evolution strip lines up; half-length poses (cheer, celebrate, thumbs_up) are cut at the
   bottom edge, as in the source.
4. Palette: 64 colours per image (max coverage, so small details like confetti keep their
   colours), no dithering.

Writes public/avatar/<phase>-<pose>.png and src/assets/avatarArt.ts. Needs Pillow only.
"""
import sys
import tempfile
import zipfile
from collections import Counter
from pathlib import Path

from PIL import Image, ImageChops

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / 'public/avatar'
TS_OUT = ROOT / 'src/assets/avatarArt.ts'

POSES = ('idle', 'cheer', 'celebrate', 'thumbs_up')
NAMES = [f'{phase}-{pose}' for phase in range(1, 6) for pose in POSES] + ['5-demo']
FULL_BODY = ('idle', 'demo')

SOURCE_SIZE = 1024
CELL = 8
SIZE = SOURCE_SIZE // CELL  # 128
# Full-body poses: the lowest row of the drawing (feet, chair or desk legs).
BASELINE = 124
COLOURS = 64
EDGE_THRESHOLD = 60


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    with tempfile.TemporaryDirectory() as tmp:
        source = unpack(Path(sys.argv[1]).expanduser(), Path(tmp))
        files = {path.stem: path for path in source.rglob('*.png')}
        missing = [name for name in NAMES if name not in files]
        extra = sorted(set(files) - set(NAMES))
        if missing:
            sys.exit(f'Faltan imágenes: {", ".join(missing)}')
        if extra:
            print(f'Se ignoran: {", ".join(extra)}')
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        for old in OUT_DIR.glob('*.png'):
            old.unlink()
        for name in NAMES:
            sprite = convert(Image.open(files[name]), name)
            sprite.save(OUT_DIR / f'{name}.png', optimize=True)
            size = (OUT_DIR / f'{name}.png').stat().st_size
            print(f'{name:14} {sprite.width}x{sprite.height}  {size // 1024} KB')
    keys = sorted(name.replace('-', ':', 1) for name in NAMES)
    TS_OUT.write_text(
        '// Generated by scripts/pixel-avatar/import.py — do not edit by hand.\n'
        '/** The avatar art that exists, as `phase:pose`. */\n'
        'export const AVATAR_ART = [\n' + ''.join(f"  '{key}',\n" for key in keys) + '] as const;\n'
    )
    print(f'{len(NAMES)} imágenes → {OUT_DIR.relative_to(ROOT)}, {TS_OUT.relative_to(ROOT)}')


def unpack(path: Path, tmp: Path) -> Path:
    if path.is_dir():
        return path
    if path.suffix == '.zip':
        with zipfile.ZipFile(path) as archive:
            archive.extractall(tmp)
        return tmp
    sys.exit(f'No es una carpeta ni un .zip: {path}')


def convert(image: Image.Image, name: str) -> Image.Image:
    image = image.convert('RGBA')
    if image.size != (SOURCE_SIZE, SOURCE_SIZE):
        image = image.resize((SOURCE_SIZE, SOURCE_SIZE), Image.Resampling.NEAREST)
    alpha = image.getchannel('A').point(lambda value: 255 if value >= 128 else 0)
    image.putalpha(alpha)
    sprite = snap(image, grid_offset(image, 'x'), grid_offset(image, 'y'))
    sprite = frame(sprite, name.split('-', 1)[1])
    return reduce_palette(sprite)


def grid_offset(image: Image.Image, axis: str) -> int:
    """The 8 px phase whose cell borders meet the most colour edges along an axis."""
    if axis == 'y':
        image = image.transpose(Image.Transpose.TRANSPOSE)
    width, height = image.size
    rgb, alpha = image.convert('RGB'), image.getchannel('A')
    a, b = rgb.crop((0, 0, width - 1, height)), rgb.crop((1, 0, width, height))
    red, green, blue = ImageChops.difference(a, b).split()
    change = ImageChops.add(ImageChops.add(red, green), blue).point(
        lambda value: 255 if value > EDGE_THRESHOLD else 0
    )
    both_opaque = ImageChops.multiply(alpha.crop((0, 0, width - 1, height)),
                                      alpha.crop((1, 0, width, height)))
    edges = ImageChops.multiply(change, both_opaque).resize((width - 1, 1), Image.Resampling.BOX)
    per_column = list(edges.tobytes())  # edge between column i and i + 1
    scores = [sum(per_column[phase::CELL]) for phase in range(CELL)]
    return (scores.index(max(scores)) + 1) % CELL


def snap(image: Image.Image, offset_x: int, offset_y: int) -> Image.Image:
    """One pixel per cell: its dominant colour, or transparent if mostly background."""
    data = image.tobytes()
    out = Image.new('RGBA', (SIZE, SIZE), (0, 0, 0, 0))
    pixels = out.load()
    # A cell's place on the 128 grid is the one its centre falls in.
    shift_x, shift_y = (offset_x + CELL // 2) // CELL, (offset_y + CELL // 2) // CELL
    for row in range((SOURCE_SIZE - offset_y) // CELL):
        for col in range((SOURCE_SIZE - offset_x) // CELL):
            x0, y0 = offset_x + col * CELL, offset_y + row * CELL
            colours = []
            transparent = 0
            for y in range(y0 + 1, y0 + CELL - 1):
                for x in range(x0 + 1, x0 + CELL - 1):
                    i = (y * SOURCE_SIZE + x) * 4
                    if data[i + 3]:
                        colours.append(data[i:i + 3])
                    else:
                        transparent += 1
            if len(colours) <= transparent:
                continue
            buckets = Counter((r >> 4, g >> 4, b >> 4) for r, g, b in colours)
            top = buckets.most_common(1)[0][0]
            chosen = [c for c in colours if (c[0] >> 4, c[1] >> 4, c[2] >> 4) == top]
            mean = tuple(round(sum(c[k] for c in chosen) / len(chosen)) for k in range(3))
            x, y = col + shift_x, row + shift_y
            if x < SIZE and y < SIZE:
                pixels[x, y] = (*mean, 255)
    return out


def frame(sprite: Image.Image, pose: str) -> Image.Image:
    """Full-body poses on a shared baseline, centred; half-length ones cut at the bottom."""
    left, top, right, bottom = sprite.getchannel('A').getbbox()
    if pose in FULL_BODY:
        dx = (SIZE - (left + right)) // 2
        dy = BASELINE - bottom
    else:
        dx = 0
        dy = SIZE - waist_row(sprite) - 1
    if top + dy < 0:
        dy = -top
    framed = Image.new('RGBA', sprite.size, (0, 0, 0, 0))
    framed.paste(sprite, (dx, dy))
    return framed


def waist_row(sprite: Image.Image) -> int:
    """The lowest row where the body (a wide run, not confetti) is cut."""
    alpha = sprite.getchannel('A').load()
    for y in range(SIZE - 1, -1, -1):
        run = longest = 0
        for x in range(SIZE):
            run = run + 1 if alpha[x, y] else 0
            longest = max(longest, run)
        if longest >= SIZE // 6:
            return y
    return SIZE - 1


def reduce_palette(sprite: Image.Image) -> Image.Image:
    alpha = sprite.getchannel('A')
    rgb = Image.new('RGB', sprite.size, (0, 0, 0))
    rgb.paste(sprite, (0, 0), sprite)
    reduced = rgb.quantize(
        colors=COLOURS, method=Image.Quantize.MAXCOVERAGE, dither=Image.Dither.NONE
    ).convert('RGBA')
    reduced.putalpha(alpha)
    return reduced


if __name__ == '__main__':
    main()
